package com.gings.utils.code;

public enum Region {
    SEOUL, SEJONG, PUSAN, DAEGU, DAEJEON, INCHEON, ULSAN, GWANGJU, JEJU,
    GANGWON, GYUNGGI, CHUNG_NAM, CHUNG_BUK, JEON_BUK, JEON_NAM, GYEONG_NAME, GYEONG_BUK, NONE;
}
